export interface ParsedResult {
  title: string;
  slug: string;
  category: string;
  author: string;
  intro: string;
  excerpt: string;
  seoTitle: string;
  seoDescription: string;
  sections: any[];
  faqs: any[];
}

/**
 * Parses raw HTML pasted from Google Docs into our Blog schema format.
 */
export function parseGoogleDocsHtml(htmlString: string): ParsedResult {
  // Use native DOMParser to parse the HTML string in the browser
  const parser = new DOMParser();
  const doc = parser.parseFromString(htmlString, "text/html");

  const result: ParsedResult = {
    title: "",
    slug: "",
    category: "",
    author: "",
    intro: "",
    excerpt: "",
    seoTitle: "",
    seoDescription: "",
    sections: [],
    faqs: [],
  };

  let currentSection: any = null;
  let currentSubsection: any = null;
  let inFaqSection = false;
  let foundFirstParagraph = false;

  // State machine for form labels
  let expectingField: keyof ParsedResult | null = null;

  // Walk through the body's direct children
  const nodes = Array.from(doc.body.childNodes);

  for (let i = 0; i < nodes.length; i++) {
    const node = nodes[i] as HTMLElement;
    if (node.nodeType !== Node.ELEMENT_NODE) continue;

    const tagName = node.tagName.toLowerCase();

    // Ignore empty tags, but preserve images or elements that might be styled blocks
    if (node.textContent?.trim() === "" && tagName !== "img" && tagName !== "br" && tagName !== "hr") {
      continue;
    }

    let plainText = node.textContent?.trim() || "";
    let lowerPlain = plainText.toLowerCase();

    // -- INLINE FIELD MATCHING (e.g., "Title:- Some title") --
    const inlineMatch = plainText.match(/^(Primary Keyword|Title|URL Slug|Slug|Category|Author|Intro Paragraph|Card Excerpt|Excerpt|SEO Title|SEO Meta Title|Description|SEO Description|SEO Meta Description)[\s*]*[:-]+\s*(.+)$/i);
    if (inlineMatch) {
      const fieldName = inlineMatch[1].toLowerCase();
      const fieldValue = inlineMatch[2].trim();
      
      if (fieldName.includes("title") && !fieldName.includes("seo")) result.title = fieldValue;
      else if (fieldName.includes("slug")) result.slug = fieldValue;
      else if (fieldName.includes("category")) result.category = fieldValue;
      else if (fieldName.includes("author")) result.author = fieldValue;
      else if (fieldName.includes("intro")) result.intro = result.intro ? result.intro + "\n\n" + fieldValue : fieldValue;
      else if (fieldName.includes("excerpt")) result.excerpt = fieldValue;
      else if (fieldName.includes("seo title")) result.seoTitle = fieldValue;
      else if (fieldName.includes("description")) result.seoDescription = fieldValue;
      else if (fieldName.includes("keyword")) {
         // Primary keyword can be added to tags or SEO Title if empty
         if (!result.seoTitle) result.seoTitle = fieldValue;
      }
      continue;
    }

    // 1. Check if this node is exactly a form label (next node will be the value)
    if (
      lowerPlain === "title *" || lowerPlain === "title" || lowerPlain === "title:"
    ) {
      expectingField = "title";
      continue;
    }
    if (
      lowerPlain === "url slug (optional - autogenerated if empty)" ||
      lowerPlain === "url slug" || lowerPlain === "slug:"
    ) {
      expectingField = "slug";
      continue;
    }
    if (lowerPlain === "category *" || lowerPlain === "category" || lowerPlain === "category:") {
      expectingField = "category";
      continue;
    }
    if (lowerPlain === "author" || lowerPlain === "author:") {
      expectingField = "author";
      continue;
    }
    if (lowerPlain === "intro paragraph" || lowerPlain === "intro paragraph:") {
      expectingField = "intro";
      continue;
    }
    if (lowerPlain === "card excerpt" || lowerPlain === "card excerpt:") {
      expectingField = "excerpt";
      continue;
    }
    if (lowerPlain === "seo meta title" || lowerPlain === "seo meta title:") {
      expectingField = "seoTitle";
      continue;
    }
    if (lowerPlain === "seo meta description" || lowerPlain === "seo meta description:") {
      expectingField = "seoDescription";
      continue;
    }

    // Ignore noise from the form
    if (/^(1\. basics|e\.g\. 10-seo-strategies|inquisitive digital|2\. hero image|upload from computer|or|paste cloudinary url\.\.\.|3\. content sections|paste from google docs|add section|no sections added yet\. click "add section" to begin writing\.|4\. faqs|add faq|5\. seo & settings)$/i.test(lowerPlain)) {
      continue;
    }

    // 2. If we were expecting a field, fill it and reset
    if (expectingField) {
      // If the field is a string in ParsedResult
      if (typeof result[expectingField] === "string") {
        (result as any)[expectingField] = node.innerHTML.trim(); // use innerHTML for intro/excerpt formatting, or text for basics
        if (["title", "slug", "category", "author", "seoTitle", "seoDescription"].includes(expectingField)) {
           (result as any)[expectingField] = plainText; // strip HTML for these basic fields
        }
      }
      expectingField = null;
      continue;
    }

    // 3. Title (H1)
    if (tagName === "h1") {
      if (!result.title) result.title = plainText;
      continue;
    }

    // 4. Sections & FAQs (H2)
    if (tagName === "h2") {
      const headingText = plainText;
      
      // Check if it's the FAQ section
      if (headingText.toLowerCase().includes("faq") || headingText.toLowerCase().includes("frequently asked questions")) {
        inFaqSection = true;
        currentSection = null;
      } else {
        inFaqSection = false;
        currentSection = {
          heading: headingText,
          subheading: "",
          text: "",
          listItems: [],
          image: { url: "", alt: "" },
          subsections: []
        };
        result.sections.push(currentSection);
        currentSubsection = null;
      }
      continue;
    }

    // 5. Subsections or FAQ Questions (H3)
    if (tagName === "h3") {
      const text = plainText;
      if (inFaqSection) {
        result.faqs.push({
          question: text,
          answer: "",
          tag: "FAQ"
        });
      } else if (currentSection) {
        currentSubsection = {
          subheading: text,
          text: "",
          listItems: [],
          image: { url: "", alt: "" }
        };
        currentSection.subsections.push(currentSubsection);
      }
      continue;
    }

    // 6. Paragraphs, Spans, Divs -> Text or Answers
    if (tagName === "p" || tagName === "span" || tagName === "div") {
      let text = node.innerHTML.trim();
      
      // Clean up weird google docs meta charset tags or empty spans if any
      text = text.replace(/<span[^>]*><\/span>/g, "");
      
      if (!text) continue;

      if (inFaqSection) {
        if (result.faqs.length > 0) {
          const lastFaq = result.faqs[result.faqs.length - 1];
          lastFaq.answer = lastFaq.answer ? lastFaq.answer + "<br><br>" + text : text;
        }
      } else if (!foundFirstParagraph && !currentSection) {
        // Collect intro paragraphs if no explicit "Intro Paragraph" was found yet
        if (!result.intro) {
          result.intro = text;
        } else {
          result.intro += "\n\n" + text;
        }
      } else if (currentSubsection) {
        currentSubsection.text = currentSubsection.text ? currentSubsection.text + "\n\n" + text : text;
      } else if (currentSection) {
        currentSection.text = currentSection.text ? currentSection.text + "\n\n" + text : text;
      }
      
      if (!inFaqSection && !currentSection) {
        foundFirstParagraph = true;
      }
      continue;
    }

    // 7. Lists -> listItems
    if (tagName === "ul" || tagName === "ol") {
      const lis = Array.from(node.querySelectorAll("li")).map(li => li.innerHTML.trim());
      if (lis.length === 0) continue;

      if (inFaqSection) {
         if (result.faqs.length > 0) {
           const lastFaq = result.faqs[result.faqs.length - 1];
           // Map lists to text with hyphens for FAQs
           lastFaq.answer += "<br>" + lis.map(li => "• " + li).join("<br>");
         }
      } else if (currentSubsection) {
        currentSubsection.listItems.push(...lis);
      } else if (currentSection) {
        currentSection.listItems.push(...lis);
      }
      continue;
    }
  }

  return result;
}
