import { FileText } from "lucide-react";
import { ServiceFullDetail } from "../types";

export const contentMarketingData: ServiceFullDetail = {
  id: "content-marketing",
  title: "Content Marketing & Blogging",
  category: "Content Marketing",
  shortDesc:
    "Attract, engage, and convert your audience with strategic content writing and blogging services designed to increase visibility, build authority, and drive long-term business growth.",
  detailedDesc:
    "Content Writing and Blogging involve creating valuable, informative, and engaging content that helps businesses attract their target audience, improve search visibility, establish authority, and generate leads. High-quality content acts as the foundation of modern digital marketing by connecting brands with potential customers at every stage of their journey.",
  icon: FileText,
  deliverables: [
    "SEO Blog Writing",
    "Website Content Creation",
    "Service Page Content",
    "Keyword Research",
    "Content Strategy",
    "Content Calendar Planning",
    "Article Writing",
    "Content Optimization",
    "Internal Linking Recommendations",
    "Performance Reporting",
  ],
  ctaText: "Get FREE consultation",
  painPoints: [
    "Generic AI articles that search engines penalize for low quality.",
    "High-effort blog writing that fails to capture organic intent.",
    "Inability to establish author credibility (E-E-A-T) on Google.",
  ],
  benefits: [
    "Expert-written, value-first articles that solve real user problems.",
    "Higher search crawl rates due to organized topic clusters.",
    "Premium downloadable resources that capture high-intent leads.",
  ],
  faq: [
    {
      q: "Why is content marketing important?",
      a: "Content marketing helps attract, engage, and convert audiences while supporting SEO and brand authority.",
    },
    {
      q: "Do you write SEO-optimized blog posts?",
      a: "Yes. Every blog is optimized for relevant keywords, user intent, and search visibility.",
    },
    {
      q: "Can you create content for any industry?",
      a: "Yes. Our process includes industry research to ensure accuracy and relevance.",
    },
    {
      q: "How often should businesses publish blogs?",
      a: "Publishing frequency depends on goals, competition, and resources, but consistency is essential.",
    },
    {
      q: "Do you provide content strategy?",
      a: "Yes. We develop content strategies aligned with business objectives and audience needs.",
    },
    {
      q: "Can content marketing generate leads?",
      a: "Absolutely. Strategic content helps attract qualified prospects and nurture them through the buying journey.",
    },
  ],
  heroSection: {
    ctaText1: "Get FREE consultation",
    ctaText2: "Explore Approach",
  },
  statsSection: {
    tag: "BY THE NUMBERS",
    heading: "Why Content Marketing Matters",
    stats: [
      {
        value: "3X",
        label: "more leads generated by content marketing compared to traditional marketing",
        source: "Demand Metric",
      },
      {
        value: "67%",
        label: "more leads generated by businesses that actively publish blogs",
        source: "HubSpot",
      },
    ],
  },
  whatIsSection: {
    tag: "WHAT IS CONTENT WRITING",
    heading: "Content Writing & Blogging Explained",
    description:
      "Content Writing and Blogging involve creating valuable, informative, and engaging content that helps businesses attract their target audience, improve search visibility, establish authority, and generate leads. High-quality content acts as the foundation of modern digital marketing by connecting brands with potential customers at every stage of their journey.",
    secondaryDescription:
      "A successful content strategy combines audience research, keyword optimization, storytelling, SEO best practices, and consistent publishing. Whether it's blog posts, website content, thought leadership articles, or industry resources, strategic content helps businesses build trust and drive sustainable growth.",
  },
  whyMattersSection: {
    tag: "WHY IT MATTERS",
    heading: "Why Content Marketing Matters for Modern Businesses",
    intro:
      "Today's consumers research before they buy. Businesses that consistently publish valuable content earn more visibility, credibility, and customer trust. Content marketing creates opportunities to attract qualified traffic, nurture prospects, and convert readers into customers.",
    benefits: [
      {
        title: "Increase Organic Traffic",
        desc: "SEO-focused content helps improve search rankings and attract qualified visitors.",
      },
      {
        title: "Build Industry Authority",
        desc: "Establish your brand as a trusted source of information within your market.",
      },
      {
        title: "Generate Qualified Leads",
        desc: "Create content that attracts and educates potential customers.",
      },
      {
        title: "Improve Search Visibility",
        desc: "Target valuable keywords and expand your digital presence.",
      },
      {
        title: "Support Sales Efforts",
        desc: "Provide prospects with valuable information that influences buying decisions.",
      },
      {
        title: "Create Long-Term Assets",
        desc: "Quality content continues generating traffic and leads long after publication.",
      },
    ],
  },
  servicesSection: {
    tag: "OUR SERVICES",
    heading: "Everything Included in Our Content Writing Service",
    services: [
      {
        title: "SEO Blog Writing",
        desc: "Search-optimized blog content designed to increase rankings, traffic, and engagement.",
      },
      {
        title: "Website Content Writing",
        desc: "Professional website copy that communicates value and drives conversions.",
      },
      {
        title: "Service Page Content",
        desc: "High-converting service pages optimized for search engines and users.",
      },
      {
        title: "Article Writing",
        desc: "Informative and authoritative articles tailored to your industry and audience.",
      },
      {
        title: "Content Strategy",
        desc: "Strategic planning to ensure content supports your business objectives.",
      },
      {
        title: "Content Optimization",
        desc: "Improve existing content for better rankings, engagement, and performance.",
      },
    ],
    seoContent: {
      tag: "SEO CONTENT",
      heading: "Content Built for Search Visibility",
      subheading: "Attract Qualified Traffic Through Strategic Content",
      description:
        "Our SEO content writing services focus on creating content that aligns with user intent, targets valuable keywords, and improves search engine visibility. Every piece is optimized to help your business rank higher and attract the right audience.",
      services: [
        "Keyword Research",
        "SEO Blog Writing",
        "Topic Cluster Development",
        "Internal Linking Strategy",
        "On-Page Optimization",
        "Content Refresh & Updates",
      ],
    },
    thoughtLeadership: {
      tag: "THOUGHT LEADERSHIP",
      heading: "Position Your Brand as an Industry Authority",
      subheading: "Build Trust Through Expert Content",
      description:
        "Thought leadership content helps businesses showcase expertise, build credibility, and establish authority within their industry. We create valuable content that strengthens your brand's reputation and attracts decision-makers.",
      services: [
        "Industry Articles",
        "Expert Insights",
        "Case Studies",
        "Research-Based Content",
        "Educational Resources",
        "Brand Storytelling",
      ],
    },
  },
  approachSection: {
    tag: "THE APPROACH",
    heading: "How We Create Content That Performs",
    mainDescription:
      "Our content creation process combines audience research, SEO strategy, storytelling, and performance analysis to produce content that drives measurable business results.",
    secondaryDescription:
      "We don't create content for the sake of publishing. Every article, blog post, and webpage is developed with a clear purpose — to attract the right audience, build trust, and support your growth objectives.",
    pills: [
      {
        title: "Audience First",
        desc: "Content created around the needs and interests of your ideal customers.",
      },
      {
        title: "SEO Driven",
        desc: "Optimized to improve visibility and organic growth.",
      },
      {
        title: "Results Focused",
        desc: "Built to support traffic, engagement, leads, and conversions.",
      },
    ],
  },
  deliverablesSection: {
    tag: "WHAT YOU GET",
    heading: "Complete Deliverables",
    items: [
      "SEO Blog Writing",
      "Website Content Creation",
      "Service Page Content",
      "Keyword Research",
      "Content Strategy",
      "Content Calendar Planning",
      "Article Writing",
      "Content Optimization",
      "Internal Linking Recommendations",
      "Performance Reporting",
    ],
    itemSubtext: "Designed to increase visibility, authority, and lead generation.",
    guaranteeText:
      "Every engagement includes strategic planning, SEO optimization, and content designed to support long-term growth.",
    guaranteeCtaText: "Build My Content Strategy",
  },
  processSection: {
    tag: "OUR PROCESS",
    heading: "Our Content Creation Process",
    steps: [
      {
        number: "01",
        title: "Research & Discovery",
        desc: "Understand your audience, industry, competitors, and goals.",
      },
      {
        number: "02",
        title: "Content Strategy",
        desc: "Develop a roadmap focused on growth, visibility, and authority.",
      },
      {
        number: "03",
        title: "Content Creation",
        desc: "Produce engaging, optimized, and audience-focused content.",
      },
      {
        number: "04",
        title: "Optimization",
        desc: "Ensure content aligns with SEO best practices and user intent.",
      },
      {
        number: "05",
        title: "Publish & Improve",
        desc: "Monitor performance and continuously improve results.",
      },
    ],
  },
  whyUsSection: {
    tag: "WHY CHOOSE US",
    heading: "The Difference We Bring",
    items: [
      {
        title: "SEO Expertise",
        desc: "Content built to improve search visibility and organic growth.",
      },
      {
        title: "Industry Research",
        desc: "Every piece is supported by research and audience insights.",
      },
      {
        title: "Quality-First Approach",
        desc: "Content that provides genuine value to readers.",
      },
      {
        title: "Strategic Planning",
        desc: "Content aligned with your business and marketing objectives.",
      },
      {
        title: "Consistent Publishing",
        desc: "Maintain a reliable content schedule that supports growth.",
      },
      {
        title: "Long-Term Results",
        desc: "Create assets that continue generating value over time.",
      },
    ],
  },
  resultsSection: {
    tag: "RESULTS YOU CAN EXPECT",
    heading: "Real Results, Real Impact",
    description:
      "Our Content Writing & Blogging Service is designed to support sustainable growth and measurable business outcomes.",
    outcomes: [
      {
        title: "Higher Search Rankings",
        desc: "Improve visibility for valuable keywords.",
      },
      {
        title: "Increased Organic Traffic",
        desc: "Attract more qualified visitors from search engines.",
      },
      {
        title: "Greater Brand Authority",
        desc: "Build trust and credibility within your industry.",
      },
      {
        title: "More Qualified Leads",
        desc: "Generate opportunities through valuable content.",
      },
      {
        title: "Improved Engagement",
        desc: "Keep visitors interested and encourage interaction.",
      },
      {
        title: "Stronger Customer Trust",
        desc: "Provide useful information that supports decision-making.",
      },
      {
        title: "Long-Term Marketing Assets",
        desc: "Create content that continues generating results.",
      },
    ],
  },
  inactionSection: {
    tag: "WHAT INACTION COSTS YOU",
    heading: "The Price of Stagnation",
    painPoints: [
      {
        title: "Generic AI articles that search engines penalize for low quality.",
        desc: "Every day without quality content allows competitors to dominate search rankings and capture your audience.",
      },
      {
        title: "High-effort blog writing that fails to capture organic intent.",
        desc: "Unoptimized content wastes resources without driving traffic, leads, or revenue.",
      },
      {
        title: "Inability to establish author credibility (E-E-A-T) on Google.",
        desc: "Without established authority, your content is ignored by both search engines and potential customers.",
      },
    ],
  },
  leadFormSection: {
    tag: "FREE CONTENT AUDIT",
    heading: "Ready to Turn Content Into Growth?",
    benefits: [
      {
        title: "Discover content opportunities.",
        desc: "Identify gaps and opportunities within your content strategy.",
      },
      {
        title: "Improve search visibility.",
        desc: "Create content that attracts more qualified traffic.",
      },
      {
        title: "Build long-term authority.",
        desc: "Position your brand as a trusted industry resource.",
      },
    ],
  },
};
